version: '3.5'

services:

  #nome do servico
  basic-python:

    #construido a partir de uma imagem customizada em ./image
    image: basic-python
    
    #nome do conteiner
    container_name: basic-python

    #pastas compartilhadas
    volumes:
      #pasta do codigo fonte da aplicacao
      - "./app:/root"
  
    #artifício para manter o container aberto
    tty: true
